#include <osgDB/Registry>

USE_SERIALIZER_WRAPPER( osgStupeflix_StupeflixStackedQuaternionElement )
USE_SERIALIZER_WRAPPER( osgStupeflix_StupeflixStackedRotateAxisElement )
USE_SERIALIZER_WRAPPER( osgStupeflix_StupeflixStackedScaleElement )
USE_SERIALIZER_WRAPPER( osgStupeflix_StupeflixStackedTranslateElement )
USE_SERIALIZER_WRAPPER( osgStupeflix_TexMat )
USE_SERIALIZER_WRAPPER( osgStupeflix_TimeGroup )
USE_SERIALIZER_WRAPPER( osgStupeflix_UniformAnimationCallbackDouble )
USE_SERIALIZER_WRAPPER( osgStupeflix_UniformAnimationCallbackFloat )
USE_SERIALIZER_WRAPPER( osgStupeflix_UniformAnimationCallbackMatrixf )
USE_SERIALIZER_WRAPPER( osgStupeflix_UniformAnimationCallbackVec2f )
USE_SERIALIZER_WRAPPER( osgStupeflix_UniformAnimationCallbackVec3f )
USE_SERIALIZER_WRAPPER( osgStupeflix_UniformAnimationCallbackVec4f )
USE_SERIALIZER_WRAPPER( osgStupeflix_UpdateMatrixTransform )
USE_SERIALIZER_WRAPPER( osgStupeflix_UpdateTexMat )
USE_SERIALIZER_WRAPPER( osgStupeflix_ImageColor )
extern "C" void wrapper_serializer_library_osgStupeflix(void) {}

